//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Diagnostics.CodeAnalysis;

namespace Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [ExcludeFromCodeCoverage]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
                
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&apos;1.0&apos; encoding=&apos;utf-8&apos;?&gt;
        ///&lt;log4net&gt;
        ///  &lt;appender name=&apos;ConsoleAppender&apos; type=&apos;log4net.Appender.ConsoleAppender&apos;&gt;
        ///    &lt;threshold value=&apos;ALL&apos; /&gt;
        ///    &lt;layout type=&apos;log4net.Layout.PatternLayout&apos;&gt;
        ///      &lt;conversionPattern value=&apos;%-5p %d [%t] %c: %m%n&apos; /&gt;
        ///    &lt;/layout&gt;
        ///  &lt;/appender&gt;
        ///  &lt;root&gt;
        ///    &lt;level value=&apos;ALL&apos; /&gt;
        ///    &lt;appender-ref ref=&apos;ConsoleAppender&apos; /&gt;
        ///  &lt;/root&gt;
        ///&lt;/log4net&gt;
        ///.
        /// </summary>
        public static string log4net {
            get {
                return ResourceManager.GetString("log4net", resourceCulture);
            }
        }
    }
}
